import json
import os
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

# ── Rate limiting ─────────────────────────────────────────────────────────────

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ── Audit log ─────────────────────────────────────────────────────────────────

LOG_FILE = "audit_log.json"


def read_log() -> list[dict]:
    """Read all entries from the audit log."""
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r", encoding="utf-8") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return []


def write_log(entries: list[dict]) -> None:
    """Write all entries back to the audit log."""
    with open(LOG_FILE, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2)


def append_log_entry(entry: dict) -> None:
    """Append a new entry to the audit log."""
    entries = read_log()
    entries.append(entry)
    write_log(entries)


def update_log_entry(content_id: str, updates: dict) -> bool:
    """
    Update an existing log entry by content_id.
    Returns True if found and updated, False if not found.
    """
    entries = read_log()
    for entry in entries:
        if entry["content_id"] == content_id:
            entry.update(updates)
            write_log(entries)
            return True
    return False


# ── Signal 1: LLM Classification (Groq) ──────────────────────────────────────

def signal_llm(text: str) -> float:
    """
    Use Groq LLM to assess whether text is AI-generated.

    Returns:
        Float between 0.0 and 1.0.
        1.0 = high confidence AI-generated
        0.0 = high confidence human-written
    """
    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

    prompt = f"""You are an AI content detection system. Analyze the following text and estimate the probability that it was generated by an AI language model rather than written by a human.

Consider these factors:
- Sentence length consistency (AI tends to be more uniform)
- Vocabulary variety and naturalness
- Presence of personal voice, emotion, or lived experience
- Overly formal or generic phrasing
- Structural perfection vs. human irregularity

Respond with ONLY a single decimal number between 0.0 and 1.0.
- 0.0 means you are highly confident this was written by a human
- 1.0 means you are highly confident this was generated by AI
- 0.5 means you are genuinely uncertain

Do not explain your reasoning. Output only the number.

Text to analyze:
{text}"""

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            max_tokens=10,
            temperature=0.0,
            messages=[{"role": "user", "content": prompt}]
        )
        raw = response.choices[0].message.content.strip()
        score = float(raw)
        # Clamp to valid range
        return max(0.0, min(1.0, score))
    except Exception as e:
        print(f"LLM signal error: {e}")
        # Return 0.5 (uncertain) on failure rather than crashing
        return 0.5


# ── Signal 2: Stylometric Heuristics (Pure Python) ───────────────────────────

def signal_stylometric(text: str) -> float:
    """
    Compute stylometric heuristics to assess whether text is AI-generated.
    Measures sentence length variance, type-token ratio, and punctuation density.

    Returns:
        Float between 0.0 and 1.0.
        1.0 = high confidence AI-generated (uniform, low-variance text)
        0.0 = high confidence human-written (varied, irregular text)
    """
    import re
    import math

    # ── Sentence splitting ────────────────────────────────────────────────────
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 0]

    # Need at least 3 sentences for meaningful analysis
    if len(sentences) < 3:
        return 0.5  # insufficient data — return uncertain

    # ── Metric 1: Sentence length variance ───────────────────────────────────
    # AI text tends to have very consistent sentence lengths
    sentence_lengths = [len(s.split()) for s in sentences]
    mean_length = sum(sentence_lengths) / len(sentence_lengths)
    variance = sum((l - mean_length) ** 2 for l in sentence_lengths) / len(sentence_lengths)
    std_dev = math.sqrt(variance)

    # Normalize: low std_dev (uniform) → high AI score
    # Typical human std_dev is 8–15 words; AI is often 3–7
    # Clamp and invert: std_dev of 0 → score 1.0, std_dev of 15+ → score 0.0
    length_variance_score = max(0.0, 1.0 - (std_dev / 15.0))

    # ── Metric 2: Type-token ratio (vocabulary diversity) ────────────────────
    # Lower TTR = less vocabulary diversity = more likely AI
    words = re.findall(r'\b[a-zA-Z]+\b', text.lower())
    if len(words) == 0:
        return 0.5
    ttr = len(set(words)) / len(words)

    # Normalize: low TTR → high AI score
    # TTR typically ranges from 0.4 (repetitive) to 0.9 (very diverse)
    # Invert and scale: TTR of 0.4 → score 1.0, TTR of 0.9 → score 0.0
    ttr_score = max(0.0, min(1.0, (0.9 - ttr) / 0.5))

    # ── Metric 3: Punctuation density ────────────────────────────────────────
    # AI text tends to use punctuation more uniformly and sparingly
    punctuation_chars = set('.,;:!?\'"-()[]{}')
    punct_count = sum(1 for c in text if c in punctuation_chars)
    punct_density = punct_count / len(text) if len(text) > 0 else 0

    # Normalize: very low or very high punctuation density → higher AI score
    # Human writing typically has 5–15% punctuation density
    # AI tends to be more uniform around 5–8%
    # Score is highest when density is very low (robotic) or very high (over-punctuated)
    optimal_human_density = 0.10
    punct_score = max(0.0, min(1.0, abs(punct_density - optimal_human_density) / 0.10))

    # ── Combine three metrics (equal weight) ─────────────────────────────────
    stylometric_score = (length_variance_score + ttr_score + punct_score) / 3.0
    return round(stylometric_score, 4)


# ── Confidence scoring ────────────────────────────────────────────────────────

def compute_confidence(llm_score: float, stylometric_score: float) -> float:
    """
    Combine LLM and stylometric scores into a single confidence score.
    Weights: 60% LLM, 40% stylometric.
    """
    return round((0.6 * llm_score) + (0.4 * stylometric_score), 4)


def get_attribution(confidence: float) -> str:
    """Map confidence score to attribution label."""
    if confidence >= 0.70:
        return "likely_ai"
    elif confidence >= 0.40:
        return "uncertain"
    else:
        return "likely_human"


# ── Transparency label ────────────────────────────────────────────────────────

def generate_label(attribution: str, confidence: float, content_id: str) -> str:
    """Generate the transparency label text shown to users."""
    score_pct = round(confidence * 100)

    if attribution == "likely_ai":
        return (
            f"⚠️ This content was likely generated by AI.\n\n"
            f"Our system analyzed the writing style and found patterns strongly "
            f"associated with AI-generated text (confidence: {score_pct}%).\n\n"
            f"If you are the human author of this work, you may submit an appeal "
            f"using your content ID: {content_id}"
        )
    elif attribution == "uncertain":
        return (
            f"❓ Our system could not confidently determine whether this content "
            f"was written by a human or generated by AI (confidence: {score_pct}%).\n\n"
            f"This label reflects genuine uncertainty — not a finding of AI generation. "
            f"If you believe this label is inaccurate, you may submit an appeal "
            f"using your content ID: {content_id}"
        )
    else:  # likely_human
        return (
            f"✅ This content appears to have been written by a human.\n\n"
            f"Our system found writing patterns consistent with human authorship "
            f"(confidence: {score_pct}%).\n\n"
            f"Content ID: {content_id}"
        )


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    """
    Accept a piece of text for attribution analysis.

    Request body (JSON):
        text (str): The content to analyze
        creator_id (str): Identifier for the creator

    Returns:
        JSON with content_id, attribution, confidence, label_text
    """
    data = request.get_json()

    # Validate input
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400
    if "text" not in data or not data["text"].strip():
        return jsonify({"error": "Field 'text' is required and cannot be empty"}), 400
    if "creator_id" not in data or not data["creator_id"].strip():
        return jsonify({"error": "Field 'creator_id' is required"}), 400

    text = data["text"].strip()
    creator_id = data["creator_id"].strip()

    # Generate unique content ID
    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    # Run detection signals
    llm_score = signal_llm(text)
    stylometric_score = signal_stylometric(text)

    # Compute confidence and attribution
    confidence = compute_confidence(llm_score, stylometric_score)
    attribution = get_attribution(confidence)
    label_text = generate_label(attribution, confidence, content_id)

    # Write audit log entry
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "label_text": label_text,
        "status": "classified",
        "appeal_reasoning": None,
        "appeal_timestamp": None
    }
    append_log_entry(log_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label_text": label_text,
        "signals": {
            "llm_score": llm_score,
            "stylometric_score": stylometric_score
        }
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    """
    Submit an appeal for a contested classification.

    Request body (JSON):
        content_id (str): The ID from the original submission
        creator_reasoning (str): The creator's explanation

    Returns:
        JSON confirmation with updated status
    """
    data = request.get_json()

    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400
    if "content_id" not in data or not data["content_id"].strip():
        return jsonify({"error": "Field 'content_id' is required"}), 400
    if "creator_reasoning" not in data or not data["creator_reasoning"].strip():
        return jsonify({"error": "Field 'creator_reasoning' is required"}), 400

    content_id = data["content_id"].strip()
    creator_reasoning = data["creator_reasoning"].strip()
    appeal_timestamp = datetime.now(timezone.utc).isoformat()

    # Update the log entry
    updated = update_log_entry(content_id, {
        "status": "under_review",
        "appeal_reasoning": creator_reasoning,
        "appeal_timestamp": appeal_timestamp
    })

    if not updated:
        return jsonify({
            "error": f"Content ID '{content_id}' not found. "
                     f"Check your content ID and try again."
        }), 404

    return jsonify({
        "message": "Your appeal has been received and is under review.",
        "content_id": content_id,
        "status": "under_review",
        "appeal_timestamp": appeal_timestamp
    })


@app.route("/log", methods=["GET"])
def get_log():
    """Return the most recent audit log entries."""
    entries = read_log()
    # Return most recent 20 entries, newest first
    recent = list(reversed(entries[-20:]))
    return jsonify({
        "total_entries": len(entries),
        "entries": recent
    })


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    app.run(debug=True, port=5000)